---
- name: Install ngnix
  hosts: dynamic__frontend #frontend.aws_ec2.yaml - keyed group name
  become: yes
  tasks:
  - name: install ngnix
    ansible.builtin.dnf:
      name: nginx
      state: present


  # ansible-playbook -i frontend.aws_ec2.yaml -e ansible_user=ec2-user -e ansible_password=De nginxyaml_Dynamic_inventory.yaml
 
